extension NumExtension on num {
  String get toArabic {
    final westernToArabic = {
      '0': '٠',
      '1': '١',
      '2': '٢',
      '3': '٣',
      '4': '٤',
      '5': '٥',
      '6': '٦',
      '7': '٧',
      '8': '٨',
      '9': '٩',
    };

    String result = toString();

    westernToArabic.forEach((latin, arabic) {
      result = result.replaceAll(latin, arabic);
    });

    return result;
  }

  String? surahNumToEngName() {
    if (this < 1 || this > 114) return null;

    const surahNames = [
      "Al-Fātiḥah",
      "Al-Baqarah",
      "Āl ʿImrān",
      "An-Nisāʾ",
      "Al-Māʾidah",
      "Al-Anʿām",
      "Al-Aʿrāf",
      "Al-Anfāl",
      "At-Tawbah",
      "Yūnus",
      "Hūd",
      "Yūsuf",
      "Ar-Raʿd",
      "Ibrāhīm",
      "Al-Ḥijr",
      "An-Naḥl",
      "Al-Isrāʾ",
      "Al-Kahf",
      "Maryam",
      "Ṭā-Hā",
      "Al-Anbiyāʾ",
      "Al-Ḥajj",
      "Al-Muʾminūn",
      "An-Nūr",
      "Al-Furqān",
      "Ash-Shuʿarāʾ",
      "An-Naml",
      "Al-Qaṣaṣ",
      "Al-ʿAnkabūt",
      "Ar-Rūm",
      "Luqmān",
      "As-Sajdah",
      "Al-Aḥzāb",
      "Sabaʾ",
      "Fāṭir",
      "Yā-Sīn",
      "As-Ṣāffāt",
      "Ṣād",
      "Az-Zumar",
      "Ghāfir",
      "Fuṣṣilat",
      "Ash-Shūrā",
      "Az-Zukhruf",
      "Ad-Dukhān",
      "Al-Jāthiyah",
      "Al-Aḥqāf",
      "Muḥammad",
      "Al-Fatḥ",
      "Al-Ḥujurāt",
      "Qāf",
      "Adh-Dhāriyāt",
      "At-Ṭūr",
      "An-Najm",
      "Al-Qamar",
      "Ar-Raḥmān",
      "Al-Wāqiʿah",
      "Al-Ḥadīd",
      "Al-Mujādilah",
      "Al-Ḥashr",
      "Al-Mumtaḥanah",
      "As-Ṣaff",
      "Al-Jumuʿah",
      "Al-Munāfiqūn",
      "At-Taghābun",
      "At-Ṭalāq",
      "At-Taḥrīm",
      "Al-Mulk",
      "Al-Qalam",
      "Al-Ḥāqqah",
      "Al-Maʿārij",
      "Nūḥ",
      "Al-Jinn",
      "Al-Muzzammil",
      "Al-Muddaththir",
      "Al-Qiyāmah",
      "Al-Insān",
      "Al-Mursalāt",
      "An-Nabaʾ",
      "An-Nāziʿāt",
      "ʿAbasa",
      "At-Takwīr",
      "Al-Infiṭār",
      "Al-Muṭaffifīn",
      "Al-Inshiqāq",
      "Al-Burūj",
      "Aṭ-Ṭāriq",
      "Al-Aʿlā",
      "Al-Ghāshiyah",
      "Al-Fajr",
      "Al-Balad",
      "Ash-Shams",
      "Al-Layl",
      "Aḍ-Ḍuḥā",
      "Ash-Sharḥ",
      "At-Tīn",
      "Al-ʿAlaq",
      "Al-Qadr",
      "Al-Bayyinah",
      "Az-Zalzalah",
      "Al-ʿĀdiyāt",
      "Al-Qāriʿah",
      "At-Takāthur",
      "Al-ʿAṣr",
      "Al-Humazah",
      "Al-Fīl",
      "Quraysh",
      "Al-Māʿūn",
      "Al-Kawthar",
      "Al-Kāfirūn",
      "An-Naṣr",
      "Al-Masad",
      "Al-Ikhlāṣ",
      "Al-Falaq",
      "An-Nās",
    ];

    return surahNames[toInt() - 1];
  }

  String? surahNumToArabicName() {
    if (this < 1 || this > 114) return null;

    const surahNames = [
      "الفاتحة",
      "البقرة",
      "آل عمران",
      "النساء",
      "المائدة",
      "الأنعام",
      "الأعراف",
      "الأنفال",
      "التوبة",
      "يونس",
      "هود",
      "يوسف",
      "الرعد",
      "إبراهيم",
      "الحجر",
      "النحل",
      "الإسراء",
      "الكهف",
      "مريم",
      "طه",
      "الأنبياء",
      "الحج",
      "المؤمنون",
      "النور",
      "الفرقان",
      "الشعراء",
      "النمل",
      "القصص",
      "العنكبوت",
      "الروم",
      "لقمان",
      "السجدة",
      "الأحزاب",
      "سبأ",
      "فاطر",
      "يس",
      "الصافات",
      "ص",
      "الزمر",
      "غافر",
      "فصلت",
      "الشورى",
      "الزخرف",
      "الدخان",
      "الجاثية",
      "الأحقاف",
      "محمد",
      "الفتح",
      "الحجرات",
      "ق",
      "الذاريات",
      "الطور",
      "النجم",
      "القمر",
      "الرحمن",
      "الواقعة",
      "الحديد",
      "المجادلة",
      "الحشر",
      "الممتحنة",
      "الصف",
      "الجمعة",
      "المنافقون",
      "التغابن",
      "الطلاق",
      "التحريم",
      "الملك",
      "القلم",
      "الحاقة",
      "المعارج",
      "نوح",
      "الجن",
      "المزمل",
      "المدثر",
      "القيامة",
      "الإنسان",
      "المرسلات",
      "النبأ",
      "النازعات",
      "عبس",
      "التكوير",
      "الانفطار",
      "المطففين",
      "الانشقاق",
      "البروج",
      "الطارق",
      "الأعلى",
      "الغاشية",
      "الفجر",
      "البلد",
      "الشمس",
      "الليل",
      "الضحى",
      "الشرح",
      "التين",
      "العلق",
      "القدر",
      "البينة",
      "الزلزلة",
      "العاديات",
      "القارعة",
      "التكاثر",
      "العصر",
      "الهمزة",
      "الفيل",
      "قريش",
      "الماعون",
      "الكوثر",
      "الكافرون",
      "النصر",
      "المسد",
      "الإخلاص",
      "الفلق",
      "الناس",
    ];

    return surahNames[toInt() - 1];
  }
}
